title: "My First Jekyll Website"
email: "test@gmail.com"
description: >-
  This is just a simple project to learn about Jekyll and his integration with Github Pages.
# baseurl: /my-first-jekyll-site
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
